import {
  INTERIM_INCIDENT_PLAYBOOK_VERSION,
  parseIncidentControlRecord,
} from "./contracts.ts";

export const incidentFixture = parseIncidentControlRecord({
  schemaVersion: 1,
  classification: "OFFICIAL",
  id: "incident-1",
  reference: "INC-2026-001",
  title: "Workplace safety occurrence",
  summary: "A workplace occurrence was reported during the morning watch.",
  status: "active",
  stage: "manageUpdate",
  playbookVersion: INTERIM_INCIDENT_PLAYBOOK_VERSION,
  occurredAt: "2026-08-01T00:00:00Z",
  openedAt: "2026-08-01T00:15:00Z",
  updatedAt: "2026-08-01T00:15:00Z",
  safety: {
    state: "confirmed",
    immediateRisk: "The affected workspace was isolated.",
    medicalOrWelfareSupport: "Medical assessment offered.",
    workplaceControls: "Access restricted pending assessment.",
    evidencePreservation: "Scene and records preserved.",
  },
  facts: ["A report was made at 1000."],
  allegations: [],
  assumptions: [],
  unknowns: ["The equipment inspection outcome is pending."],
  actions: [],
  notifications: {
    commandNotifiedAt: "2026-08-01T00:10:00Z",
    specialists: ["Safety"],
    note: "Command and Safety were notified separately.",
  },
  reporting: {
    formalReportStatus: "inProgress",
    note: "N1 is preparing the initial report.",
  },
  lastReviewedAt: "2026-08-01T00:15:00Z",
  nextReviewAt: "2026-08-15T00:15:00Z",
  lastDecmsUpdatedAt: "2026-08-01T00:15:00Z",
  decmsReference: "DECMS-001",
  reviews: [],
  closure: {
    actionsComplete: false,
    outcomesRecorded: false,
    partiesAdvised: false,
    supportConcluded: false,
    handoverComplete: false,
    lessonsIdentified: false,
    repeatPatternChecked: false,
    evidence: null,
  },
});
